---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/6 15:40
---
require("Config.ItemCfg")
local newItem={};
PlayerCache = {
    id,
    name,
    gold,
    diamond,
    addAtk=0,
    addDef=0,
    item={},
    role={},
    nowRole,
    roleAtk=0,
    roleDef=0,
    roleHp=0,
}

function PlayerCache.AddBagItem(itemid)
    newItem =  ItemCfg.GetItemCfg(itemid);
     PlayerCache.item[itemid]=newItem;
end

function PlayerCache.GetBagItem(itemid)
    return PlayerCache.item[tonumber(itemid)];
end


