---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/1 12:40
---
require "Common/define"
--require "3rd/pbc/protobuf"
require "pblua.bag_pb"
require("Global.PlayerCache")
require("Config.ItemCfg")
require("View.RoleWnd")
BagWnd = {
    thisBtn={},
}
local this = BagWnd
local btnReturn;

local btnHead;
local btnArm;
local btnChest;

local contentHead;
local contentArm;
local contentChest;

local img;
local btnWear;

local head;
local arm;
local chest;
local child;

headid=0;
armid=0;
chestid=0;

local atkText
local defText;
local hpText;

local bagLook;
local thisRender;
--构建函数--
function BagWnd.New()
    return this;
end

function BagWnd.Open()
    panelMgr:CreatePanel("UI", 'BagWnd', this.OnCreate);
end

--启动事件--
function BagWnd.OnCreate(obj)
    gameObject = obj;
    transform = obj.transform;

    behavior = transform:GetComponent('LuaBehaviour');
    btnReturn = transform:Find("Title/BtnReturn").gameObject;
    behavior:AddClick(btnReturn,this.OnBtnReturn);

    atkText=transform:Find("Atk"):GetComponent("Text");
    defText=transform:Find("Def"):GetComponent("Text");
    hpText=transform:Find("Hp"):GetComponent("Text");

    head=transform:Find("Head/Image"):GetComponent("Image");
    arm=transform:Find("Arm/Image"):GetComponent("Image");
    chest=transform:Find("Chest/Image"):GetComponent("Image");

    btnHead=transform:Find("HeadScroll View/Viewport/Item");
    btnArm=transform:Find("ArmScroll View/Viewport/Item");
    btnChest=transform:Find("ChestScroll View/Viewport/Item");

    contentHead=transform:Find("HeadScroll View/Viewport/Content");
    contentArm=transform:Find("ArmScroll View/Viewport/Content");
    contentChest=transform:Find("ChestScroll View/Viewport/Content");

    bagLook=transform:Find("Look"):GetComponent("RawImage");
    RoleWnd.LoadRole();

    for i, v in pairsByKeys(PlayerCache.item) do
        if type(PlayerCache.item) == "table" then
            equip = PlayerCache.item[i];
            child={};
            if equip.EquipType=="0" then
                BagWnd.SetBtnParent(btnHead,contentHead);
            elseif equip.EquipType=="1" then
                BagWnd.SetBtnParent(btnArm,contentArm);
            elseif equip.EquipType=="2" then
                BagWnd.SetBtnParent(btnChest,contentChest);
            end
            child.localScale = Vector3.one;
            child.localPosition = Vector3.zero;
            child.gameObject:SetActive(true);
            child.name = equip.ID;
            img = resMgr:LoadSprite("Icon", equip.Icon,equip.Icon);
            child:Find("Image"):GetComponent("Image").overrideSprite=img;
            child:Find("Name"):GetComponent("Text").text = equip.Name;

            -- 给每一个按钮添加事件
            btnWear= child:Find("Button");
            btnWear.name=equip.ID;
            behavior:AddClick(child:Find(btnWear.name).gameObject, this.OnBtnWear);
        end
    end
    BagWnd.LoadEquip();
end

function BagWnd.OnBtnWear(go)
    BagWnd.thisBtn=nil;
    BagWnd.thisBtn=go;
    local item= PlayerCache.GetBagItem(BagWnd.thisBtn.name);
    local req = bag_pb.ReqWear();
    req.id=tonumber(PlayerCache.id);
    req.itemId=tonumber(item.ID);
    req.attrType=tonumber(item.AttrType);
    req.attrValue=tonumber(item.AttrValue);
    req.equipType=tonumber(item.EquipType);
    local msg = req:SerializeToString();

    local buffer = ByteArray.New();
    buffer:write(msg);
    networkMgr:SendMessage(msgid.INV_Equip_CREQ, buffer);
end

function BagWnd.WearWhat(item,go)
    if item.EquipType=="0" then
        headid=tonumber(go.name);
        BagWnd.Wear(head,item,go);
    elseif item.EquipType=="1" then
        armid=tonumber(go.name);
        BagWnd.Wear(arm,item,go);
    elseif item.EquipType=="2" then
        chestid=tonumber(go.name);
        BagWnd.Wear(chest,item,go);
    end
end

function BagWnd.Wear(bagImage,item,go)
    local image=  resMgr:LoadSprite("Icon", item.Icon,item.Icon);
    if
         bagImage.name=="Image"
    then
        bagImage.overrideSprite=image;
        bagImage.name=item.ID;
        local thisImage=go.transform.parent;
        destroy(thisImage.gameObject);
    else
        local cache=PlayerCache.GetBagItem(bagImage.name);
        local LastImage=resMgr:LoadSprite("Icon", cache.Icon,cache.Icon);
        local thisImage=go.transform.parent;
        thisImage.transform:Find("Image"):GetComponent("Image").overrideSprite=LastImage;
        bagImage.overrideSprite=image;
        thisImage.name=bagImage.name;
        bagImage.name=item.ID;
        go.name=thisImage.name;
    end
end

function BagWnd.LoadEquip()
    if headid~=0 then
        head.overrideSprite=BagWnd.LoadImage(headid);
        head.name=headid;
        destroy(contentHead.transform:Find(headid).gameObject);
    end
    if armid~=0 then
        arm.overrideSprite=BagWnd.LoadImage(armid);
        arm.name=armid;
        destroy(contentArm.transform:Find(armid).gameObject);
    end
    if chestid~=0 then
        chest.overrideSprite=BagWnd.LoadImage(chestid);
        chest.name=chestid;
        destroy(contentChest.transform:Find(chestid).gameObject);
    end
    BagWnd.Refresh();
end

function BagWnd.LoadImage(id)
    local cache=PlayerCache.GetBagItem(id);
    local Image=resMgr:LoadSprite("Icon", cache.Icon,cache.Icon);
    return Image;
end

function BagWnd.SetBtnParent(btn,content)
   child = GameObject.Instantiate(btn.gameObject).transform;
   child:SetParent(content);
end

function BagWnd.Refresh()
    atkText.text=tostring(PlayerCache.addAtk+PlayerCache.roleAtk);
    defText.text=tostring(PlayerCache.addDef+PlayerCache.roleDef);
    hpText.text=tostring(PlayerCache.roleHp);

    thisRender = resMgr:LoadRenderTexture("Render", "TexC" ..PlayerCache.nowRole, "TexC" ..PlayerCache.nowRole);
    bagLook.texture=thisRender;
end

-- 返回按钮的点击事件
function BagWnd.OnBtnReturn(go)
        BagWnd.Close();
end

--关闭事件--
function BagWnd.Close()
    panelMgr:ClosePanel(CtrlNames.BagWnd);
end