---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/9 9:03
---
require "Common/define"
require "pblua.role_pb"
require("Global.PlayerCache")
require("Config.RoleCfg")
RoleWnd = {
    camera = {},
    btnRole = {},
    Render={}
}
local this = RoleWnd
local btnReturn;

local thisParent;
local thisRole;
local thisRoleLook;

local parent;
local go;

local content;
local roleLook;

local lenceMax = 1008;
local lenceMin = 1001;

local roleGold;
local roleDiamond;

local btnSet = {};
local lastBtnSet = {};
--构建函数--
function RoleWnd.New()
    return this;
end

function RoleWnd.Open()
    panelMgr:CreatePanel("UI", 'RoleWnd', this.OnCreate);
end

--启动事件--
function RoleWnd.OnCreate(obj)
    gameObject = obj;
    transform = obj.transform;
    behavior = transform:GetComponent('LuaBehaviour');
    btnReturn = transform:Find("Title/BtnReturn").gameObject;
    behavior:AddClick(btnReturn, this.OnBtnReturn);

    content = transform:Find("Scroll View/Viewport/Content");
    roleLook = transform:Find("Scroll View/Viewport/Role");

    RoleWnd.SetFalse();
    roleGold = transform:Find("Title/GoldInfo/TxtGold");
    roleDiamond = transform:Find("Title/GoldInfo/TxtDiamond");
    RoleWnd.SetHave(PlayerCache.gold, PlayerCache.diamond);
    RoleWnd.LoadRole();
    RoleWnd.LoadLook();
end

function RoleWnd.LoadRole()
    parent = find("Role");
    if parent == nil then
        parent = find("GameObject").transform;
        go = GameObject.Instantiate(parent.gameObject).transform;
        go:SetParent(parent);
    end
    if parent.name ~= "Role" then
        for i = lenceMin, lenceMax do
            thisParent = GameObject.Instantiate(parent.transform:Find(go.name).gameObject).transform;
            thisParent:SetParent(parent);
            resMgr:LoadPrefab("Units", "C" .. i, { "C" .. i }, RoleWnd.OnLoadFinish);
            thisParent.name = "C" .. i;
            thisRole.name = "C" .. i;

            resMgr:LoadPrefab("Units", "Camera", { "Camera" }, RoleWnd.OnLoadFinish );
            thisParent.localPosition = Vector3((i - 1000) * 5 + 400, 1, 4);
            thisRole.name = "C" .. i .. "Camera";
            RoleWnd.camera[i] = thisRole;
            RoleWnd.Render[i] = {};
            RoleWnd.Render[i]=resMgr:LoadRenderTexture("Render", "TexC" .. i, "TexC" .. i);
            RoleWnd.camera[i]:GetComponent("Camera").targetTexture = RoleWnd.Render[i];
        end
    end
    parent.name = "Role";
end

function RoleWnd.LoadLook()
    for i = lenceMin, lenceMax do
        thisRoleLook = GameObject.Instantiate(roleLook.gameObject).transform;
        thisRoleLook:SetParent(content);
        thisRoleLook.localScale = Vector3.one;
        thisRoleLook.localPosition = Vector3.zero;
        thisRoleLook.name = "C" .. i;
        local cfg = RoleCfg.GetRole(i);
        thisRoleLook:Find("Name"):GetComponent("Text").text = cfg.RoleName;

        thisRoleLook:Find("Look"):GetComponent("RawImage").texture = RoleWnd.Render[i];
        thisRoleLook:Find("Look").name = "Look" .. "C" .. i;
        thisRoleLook.gameObject:SetActive(true);
        behavior:AddClick(thisRoleLook:Find("Look" .. "C" .. i).gameObject, this.OnBtnLook);

        local btn = thisRoleLook:Find("BtnBuy");
        btn.name = "BtnBuy" .. "C" .. i;
        btn.transform:Find("Text"):GetComponent("Text").text = cfg.Money;
        behavior:AddClick(thisRoleLook:Find("BtnBuy" .. "C" .. i).gameObject, this.OnBtnBuy);
        RoleWnd.RefreshButton(thisRoleLook:Find("BtnBuy" .. "C" .. i).gameObject);

        thisRoleLook:Find("BtnUse").name = "BtnUse" .. "C" .. i;
        RoleWnd.RefreshSet(thisRoleLook:Find("BtnUse" .. "C" .. i).gameObject);
        behavior:AddClick(thisRoleLook:Find("BtnUse" .. "C" .. i).gameObject, this.OnBtnUse);
    end
end
function RoleWnd.OnBtnUse(go)
    lastBtnSet = btnSet;
    btnSet = nil;
    btnSet = go;

    local req = role_pb.ReqSetRole();
    req.roleId = tonumber(string.sub(go.name, 8, 11));
    req.id = PlayerCache.id;
    local buffer = ByteArray.New();
    local msg = req:SerializeToString();
    buffer:write(msg);
    networkMgr:SendMessage(msgid.CHAR_ONLINE_CREQ, buffer);
end

function RoleWnd.OnBtnBuy(go)
    RoleWnd.btnRole = nil;
    RoleWnd.btnRole = go;

    local req = role_pb.ReqBuyRole();
    req.id = PlayerCache.id;
    req.roleId = tonumber(string.sub(go.name, 8, 11));

    local buffer = ByteArray.New();
    local msg = req:SerializeToString();
    buffer:write(msg);
    networkMgr:SendMessage(msgid.CHAR_CREATE_CREQ, buffer);
end
function RoleWnd.OnBtnLook(go)
    local cfg = RoleCfg.GetRole(string.sub(go.transform.parent.name, 2, 5));
    MessageBox.Open();
    MessageBox.Show("角色名:" .. cfg.RoleName .. "\n" .. "血量:" .. cfg.Hp .. "\n" .. "攻击:" .. cfg.Atk .. "\n" .. "防御:" .. cfg.Def);
end

function RoleWnd.OnLoadFinish(objs)
    thisRole = UnityEngine.GameObject.Instantiate(objs[0]).transform;
    thisRole:SetParent(thisParent);
    thisRole.localScale = Vector3.one;
    LuaFramework.Util.Log("实例化完毕");
end

function RoleWnd.SetHave(gold, diamond)
    roleGold:GetComponent("Text").text = gold;
    roleDiamond:GetComponent("Text").text = diamond;
end

function RoleWnd.SetFalse()
    for i = 1, content.childCount do
        local child = content:GetChild(i - 1);
        child:Find("BtnUse" .. child.name):GetComponent("Button").interactable = true;
        child:Find("BtnUse" .. child.name):Find("Text"):GetComponent("Text").text = "设置出战角色";
        if child.name == "C" .. PlayerCache.nowRole then
            child:Find("BtnUse" .. child.name):GetComponent("Button").interactable = false;
            child:Find("BtnUse" .. child.name):Find("Text"):GetComponent("Text").text = "出战中";
        end
    end
end

function RoleWnd.RefreshButton(btn)
    for i, v in pairs(PlayerCache.role) do
        if type(i) ~= "table" and tonumber(string.sub(btn.name, 8, 11)) == v then
            btn:SetActive(false);
        end
    end
end

function RoleWnd.RefreshSet(btn)
    if tonumber(string.sub(btn.name, 8, 11))==PlayerCache.nowRole then
        btn:GetComponent("Button").interactable = false;
        btn.transform:Find("Text"):GetComponent("Text").text = "出战中";
    end
end

-- 返回按钮的点击事件
function RoleWnd.OnBtnReturn(go)
    RoleWnd.Close();
end

--关闭事件--
function RoleWnd.Close()
    panelMgr:ClosePanel(CtrlNames.RoleWnd);
end
