---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shang.
--- DateTime: 2018/3/13 14:50
---


require("Common.define")
require("Config.DungeonCfg")
require("pblua.selectdungeon_pb")

SelectDungeonWnd = {}
local this = SelectDungeonWnd

local btnReturn;
local content;
local btnBattle;

--构建函数--
function SelectDungeonWnd.New()
    return this;
end

function SelectDungeonWnd.Open()
    panelMgr:CreatePanel("UI", 'SelectDungeonWnd', this.OnCreate);
end

--启动事件--
function SelectDungeonWnd.OnCreate(obj)
    gameObject = obj;
    transform = obj.transform;

    behavior = transform:GetComponent('LuaBehaviour');

    -- 给返回按钮添加事件
    btnReturn = transform:Find("BtnReturn").gameObject;
    behavior:AddClick(btnReturn, this.OnBtnReturn);

    content = transform:Find("Scroll View/Viewport/Content");
    btnBattle = transform:Find("Scroll View/Viewport/BtnBattle");

    -- 依据选择副本的配置初始化滚动视图
    for i, v in pairsByKeys(DungeonCfg) do
        if type(v) == "table" then
            cfg = DungeonCfg[i];

            child = GameObject.Instantiate(btnBattle.gameObject).transform;
            child:SetParent(content);
            child.localScale = Vector3.one;
            child.localPosition = Vector3.zero;
            child.gameObject:SetActive(true);
            child.name = cfg.ID;
            child:Find("Text"):GetComponent("Text").text = cfg.Name;

            -- 给每一个按钮添加事件
            behavior:AddClick(child.gameObject, this.OnBtnBattleClick);
        end
    end

end

function SelectDungeonWnd.OnBtnBattleClick(go)
    print(go.name)
    local req = selectdungeon_pb.ReqSelectDungeon();
    req.dungeonid = tonumber(go.name);
    local msg = req:SerializeToString();

    local buffer = ByteArray.New();
    buffer:write(msg);
    networkMgr:SendMessage(msgid.ReqSelectDungeon, buffer);
end

-- 返回按钮的点击事件
function SelectDungeonWnd.OnBtnReturn(go)
    SelectDungeonWnd.Close();
end


--关闭事件--
function SelectDungeonWnd.Close()
    panelMgr:ClosePanel(CtrlNames.SelectDungeonWnd);
end