//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: bag.proto
// Note: requires additional types generated from: common.proto
namespace bag
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqWear")]
  public partial class ReqWear : global::ProtoBuf.IExtensible
  {
    public ReqWear() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _attrType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attrType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrType
    {
      get { return _attrType; }
      set { _attrType = value; }
    }
    private int _attrValue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"attrValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrValue
    {
      get { return _attrValue; }
      set { _attrValue = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _equipType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"equipType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipType
    {
      get { return _equipType; }
      set { _equipType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspWear")]
  public partial class RspWear : global::ProtoBuf.IExtensible
  {
    public RspWear() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _atk;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}