//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mall.proto
// Note: requires additional types generated from: common.proto
namespace mall
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuy")]
  public partial class ReqBuy : global::ProtoBuf.IExtensible
  {
    public ReqBuy() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspBuy")]
  public partial class RspBuy : global::ProtoBuf.IExtensible
  {
    public RspBuy() {}
    
    private int _lastGold;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lastGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastGold
    {
      get { return _lastGold; }
      set { _lastGold = value; }
    }
    private int _lastDiamond;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastDiamond
    {
      get { return _lastDiamond; }
      set { _lastDiamond = value; }
    }
    private uint _msgtips;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}