//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: role.proto
// Note: requires additional types generated from: common.proto
namespace role
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyRole")]
  public partial class ReqBuyRole : global::ProtoBuf.IExtensible
  {
    public ReqBuyRole() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspBuyRole")]
  public partial class RspBuyRole : global::ProtoBuf.IExtensible
  {
    public RspBuyRole() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _lastGold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastGold
    {
      get { return _lastGold; }
      set { _lastGold = value; }
    }
    private uint _msgtips;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSetRole")]
  public partial class ReqSetRole : global::ProtoBuf.IExtensible
  {
    public ReqSetRole() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspSetRole")]
  public partial class RspSetRole : global::ProtoBuf.IExtensible
  {
    public RspSetRole() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _roleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private int _atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _Hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}