//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: selectdungeon.proto
namespace selectdungeon
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSelectDungeon")]
  public partial class ReqSelectDungeon : global::ProtoBuf.IExtensible
  {
    public ReqSelectDungeon() {}
    
    private int _dungeonid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonid
    {
      get { return _dungeonid; }
      set { _dungeonid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspSelectDungeon")]
  public partial class RspSelectDungeon : global::ProtoBuf.IExtensible
  {
    public RspSelectDungeon() {}
    
    private int _dungeonid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonid
    {
      get { return _dungeonid; }
      set { _dungeonid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLeaveDungeon")]
  public partial class ReqLeaveDungeon : global::ProtoBuf.IExtensible
  {
    public ReqLeaveDungeon() {}
    
    private int _dungeonid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonid
    {
      get { return _dungeonid; }
      set { _dungeonid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspLeveaDungeon")]
  public partial class RspLeveaDungeon : global::ProtoBuf.IExtensible
  {
    public RspLeveaDungeon() {}
    
    private int _dungeonid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dungeonid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeonid
    {
      get { return _dungeonid; }
      set { _dungeonid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}