---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shang.
--- DateTime: 2018/3/15 14:34
---

require("Common.msgid")
require("Global.ConfigManager")
require("Config.MsgTipsCfg")
require("Global.DataCache")


DungeonHandler = {};
local this = DungeonHandler;

function DungeonHandler.Register()
    networkMgr:Register(msgid.RspSelectDungeon, DungeonHandler.OnSelectDungeon);
    networkMgr:Register(msgid.RspLeveaDungeon, DungeonHandler.OnLeaveDungeon);
end

function DungeonHandler.OnSelectDungeon(m)
    local msg = selectdungeon_pb.RspSelectDungeon();
    local data = ByteArray.GetBuffer(m.message);
    msg:ParseFromString(data);


    DataCache.battleid = tostring(msg.dungeonid);
    local cfg = DungeonCfg.GetDungeonCfg(DataCache.battleid)

    SelectDungeonWnd.Close()
    MainWnd.Close()
    Loading.LoadScene(cfg.Scene)
end

function DungeonHandler.OnLeaveDungeon(m)
    local msg = selectdungeon_pb.RspLeveaDungeon();
    local data = ByteArray.GetBuffer(m.message);
    msg:ParseFromString(data);

    BattleWnd.Close();
    battleMgr.Clear();
    Loading.LoadScene("MainScene");
end
