---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/12 9:38
---
require("Common.msgid")
require("Global.PlayerCache")
require("View.RoleWnd")
RoleHandler = {};
local this = RoleHandler;

function RoleHandler.Register()
    networkMgr:Register(msgid.CHAR_CREATE_SRES, RoleHandler.OnRspBuy);
    networkMgr:Register(msgid.CHAR_ONLINE_SRES, RoleHandler.OnRspSet);
end

function RoleHandler.OnRspSet(m)
    local msg = role_pb.RspSetRole();
    local data = ByteArray.GetBuffer(m.message);
    msg:ParseFromString(data);

    PlayerCache.nowRole=msg.roleId;
    PlayerCache.roleAtk=msg.atk;
    PlayerCache.roleDef=msg.def;
    PlayerCache.roleHp=msg.Hp;

    RoleWnd.SetFalse();
    MessageBox.Open();
    MessageBox.Show(msg.roleName.."已上阵");
end

function RoleHandler.OnRspBuy(m)
    local msg = role_pb.RspBuyRole();
    local data = ByteArray.GetBuffer(m.message);
    msg:ParseFromString(data);
    if msg.msgtips==1011 then
        PlayerCache.gold=msg.lastGold;
        table.insert(PlayerCache.role,msg.roleId);
        RoleWnd.SetHave(PlayerCache.gold,PlayerCache.diamond);
        MessageBox.Open();
        MessageBox.Show("解锁成功");
        RoleWnd.btnRole:SetActive(false);
    else
        MessageBox.Open();
        MessageBox.Show("金币或钻石不足");
    end
end