---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shang.
--- DateTime: 2018/3/12 10:08
---

require("Common.define")
require("pblua.selectdungeon_pb")

BattleWnd = {}
local this = BattleWnd

local btnReturn;

--构建函数--
function BattleWnd.New()
    return this;
end

function BattleWnd.Open()
    panelMgr:CreatePanel("UI", 'BattleWnd', this.OnCreate);
end

--启动事件--
function BattleWnd.OnCreate(obj)
    gameObject = obj;
    transform = obj.transform;

    behavior = transform:GetComponent('LuaBehaviour');
    btnReturn = transform:Find("BtnReturn").gameObject;
    behavior:AddClick(btnReturn, this.OnBtnReturn);
end

-- 返回按钮的点击事件
function BattleWnd.OnBtnReturn(go)
    --BattleWnd.Close();
    --Loading.LoadScene("MainScene")
    BattleWnd.Close();
    local req = selectdungeon_pb.ReqLeaveDungeon();
    req.dungeonid = 0;
    local msg = req:SerializeToString();

    local buffer = ByteArray.New();
    buffer:write(msg);
    networkMgr:SendMessage(msgid.ReqLeaveDungeon, buffer);
end


--关闭事件--
function BattleWnd.Close()
    panelMgr:ClosePanel(CtrlNames.BattleWnd);
end