---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shang.
--- DateTime: 2018/3/13 9:12
---

MainWnd = {}
local this = MainWnd

local behavior;
local btnReturn;
local btnBattle;
local btnRole;
local btnBag;
local btnMall;

--构建函数--
function MainWnd.New()
    return this;
end

function MainWnd.Open()
    panelMgr:CreatePanel("UI", 'MainWnd', this.OnCreate);
end

--启动事件--
function MainWnd.OnCreate(obj)
    gameObject = obj;
    transform = obj.transform;

    behavior = transform:GetComponent('LuaBehaviour');
    --btnReturn = transform:Find("Title/BtnReturn").gameObject;
    btnBattle = transform:Find("BtnBattle").gameObject;
    btnBag=transform:Find("BtnBag").gameObject;
    btnRole=transform:Find("BtnRole").gameObject;
    btnMall=transform:Find("BtnMall").gameObject;


    --behavior:AddClick(btnReturn, this.OnBtnReturn);
    behavior:AddClick(btnBattle, this.OnBtnBattle);
    behavior:AddClick(btnBag,this.OnBtnBag);
    behavior:AddClick(btnRole,this.OnBtnRole);
    behavior:AddClick(btnMall,this.OnBtnMall);
end

-- 返回按钮的点击事件
function MainWnd.OnBtnReturn(go)
    MainWnd.Close();
    Loading.LoadScene("Login")
end

-- 进入战斗的点击事件
function MainWnd.OnBtnBattle(go)
    SelectDungeonWnd.Open();
end

function MainWnd.OnBtnBag(go)
      BagWnd.Open();
end

function MainWnd.OnBtnRole(go)
      RoleWnd.Open();
end

function MainWnd.OnBtnMall(go)
       MallWnd.Open();
end

--关闭事件--
function MainWnd.Close()
    panelMgr:ClosePanel(CtrlNames.MainWnd);
end