-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local common_pb = require("common_pb")
module('role_pb')


local REQBUYROLE = protobuf.Descriptor();
local REQBUYROLE_ID_FIELD = protobuf.FieldDescriptor();
local REQBUYROLE_ROLEID_FIELD = protobuf.FieldDescriptor();
local RSPBUYROLE = protobuf.Descriptor();
local RSPBUYROLE_ROLEID_FIELD = protobuf.FieldDescriptor();
local RSPBUYROLE_LASTGOLD_FIELD = protobuf.FieldDescriptor();
local RSPBUYROLE_MSGTIPS_FIELD = protobuf.FieldDescriptor();
local REQSETROLE = protobuf.Descriptor();
local REQSETROLE_ID_FIELD = protobuf.FieldDescriptor();
local REQSETROLE_ROLEID_FIELD = protobuf.FieldDescriptor();
local RSPSETROLE = protobuf.Descriptor();
local RSPSETROLE_ROLEID_FIELD = protobuf.FieldDescriptor();
local RSPSETROLE_ROLENAME_FIELD = protobuf.FieldDescriptor();
local RSPSETROLE_ATK_FIELD = protobuf.FieldDescriptor();
local RSPSETROLE_DEF_FIELD = protobuf.FieldDescriptor();
local RSPSETROLE_HP_FIELD = protobuf.FieldDescriptor();

REQBUYROLE_ID_FIELD.name = "id"
REQBUYROLE_ID_FIELD.full_name = ".ReqBuyRole.id"
REQBUYROLE_ID_FIELD.number = 1
REQBUYROLE_ID_FIELD.index = 0
REQBUYROLE_ID_FIELD.label = 2
REQBUYROLE_ID_FIELD.has_default_value = false
REQBUYROLE_ID_FIELD.default_value = 0
REQBUYROLE_ID_FIELD.type = 5
REQBUYROLE_ID_FIELD.cpp_type = 1

REQBUYROLE_ROLEID_FIELD.name = "roleId"
REQBUYROLE_ROLEID_FIELD.full_name = ".ReqBuyRole.roleId"
REQBUYROLE_ROLEID_FIELD.number = 2
REQBUYROLE_ROLEID_FIELD.index = 1
REQBUYROLE_ROLEID_FIELD.label = 2
REQBUYROLE_ROLEID_FIELD.has_default_value = false
REQBUYROLE_ROLEID_FIELD.default_value = 0
REQBUYROLE_ROLEID_FIELD.type = 5
REQBUYROLE_ROLEID_FIELD.cpp_type = 1

REQBUYROLE.name = "ReqBuyRole"
REQBUYROLE.full_name = ".ReqBuyRole"
REQBUYROLE.nested_types = {}
REQBUYROLE.enum_types = {}
REQBUYROLE.fields = {REQBUYROLE_ID_FIELD, REQBUYROLE_ROLEID_FIELD}
REQBUYROLE.is_extendable = false
REQBUYROLE.extensions = {}
RSPBUYROLE_ROLEID_FIELD.name = "roleId"
RSPBUYROLE_ROLEID_FIELD.full_name = ".RspBuyRole.roleId"
RSPBUYROLE_ROLEID_FIELD.number = 1
RSPBUYROLE_ROLEID_FIELD.index = 0
RSPBUYROLE_ROLEID_FIELD.label = 2
RSPBUYROLE_ROLEID_FIELD.has_default_value = false
RSPBUYROLE_ROLEID_FIELD.default_value = 0
RSPBUYROLE_ROLEID_FIELD.type = 5
RSPBUYROLE_ROLEID_FIELD.cpp_type = 1

RSPBUYROLE_LASTGOLD_FIELD.name = "lastGold"
RSPBUYROLE_LASTGOLD_FIELD.full_name = ".RspBuyRole.lastGold"
RSPBUYROLE_LASTGOLD_FIELD.number = 2
RSPBUYROLE_LASTGOLD_FIELD.index = 1
RSPBUYROLE_LASTGOLD_FIELD.label = 2
RSPBUYROLE_LASTGOLD_FIELD.has_default_value = false
RSPBUYROLE_LASTGOLD_FIELD.default_value = 0
RSPBUYROLE_LASTGOLD_FIELD.type = 5
RSPBUYROLE_LASTGOLD_FIELD.cpp_type = 1

RSPBUYROLE_MSGTIPS_FIELD.name = "msgtips"
RSPBUYROLE_MSGTIPS_FIELD.full_name = ".RspBuyRole.msgtips"
RSPBUYROLE_MSGTIPS_FIELD.number = 3
RSPBUYROLE_MSGTIPS_FIELD.index = 2
RSPBUYROLE_MSGTIPS_FIELD.label = 2
RSPBUYROLE_MSGTIPS_FIELD.has_default_value = false
RSPBUYROLE_MSGTIPS_FIELD.default_value = 0
RSPBUYROLE_MSGTIPS_FIELD.type = 13
RSPBUYROLE_MSGTIPS_FIELD.cpp_type = 3

RSPBUYROLE.name = "RspBuyRole"
RSPBUYROLE.full_name = ".RspBuyRole"
RSPBUYROLE.nested_types = {}
RSPBUYROLE.enum_types = {}
RSPBUYROLE.fields = {RSPBUYROLE_ROLEID_FIELD, RSPBUYROLE_LASTGOLD_FIELD, RSPBUYROLE_MSGTIPS_FIELD}
RSPBUYROLE.is_extendable = false
RSPBUYROLE.extensions = {}
REQSETROLE_ID_FIELD.name = "id"
REQSETROLE_ID_FIELD.full_name = ".ReqSetRole.id"
REQSETROLE_ID_FIELD.number = 1
REQSETROLE_ID_FIELD.index = 0
REQSETROLE_ID_FIELD.label = 2
REQSETROLE_ID_FIELD.has_default_value = false
REQSETROLE_ID_FIELD.default_value = 0
REQSETROLE_ID_FIELD.type = 5
REQSETROLE_ID_FIELD.cpp_type = 1

REQSETROLE_ROLEID_FIELD.name = "roleId"
REQSETROLE_ROLEID_FIELD.full_name = ".ReqSetRole.roleId"
REQSETROLE_ROLEID_FIELD.number = 2
REQSETROLE_ROLEID_FIELD.index = 1
REQSETROLE_ROLEID_FIELD.label = 2
REQSETROLE_ROLEID_FIELD.has_default_value = false
REQSETROLE_ROLEID_FIELD.default_value = 0
REQSETROLE_ROLEID_FIELD.type = 5
REQSETROLE_ROLEID_FIELD.cpp_type = 1

REQSETROLE.name = "ReqSetRole"
REQSETROLE.full_name = ".ReqSetRole"
REQSETROLE.nested_types = {}
REQSETROLE.enum_types = {}
REQSETROLE.fields = {REQSETROLE_ID_FIELD, REQSETROLE_ROLEID_FIELD}
REQSETROLE.is_extendable = false
REQSETROLE.extensions = {}
RSPSETROLE_ROLEID_FIELD.name = "roleId"
RSPSETROLE_ROLEID_FIELD.full_name = ".RspSetRole.roleId"
RSPSETROLE_ROLEID_FIELD.number = 1
RSPSETROLE_ROLEID_FIELD.index = 0
RSPSETROLE_ROLEID_FIELD.label = 2
RSPSETROLE_ROLEID_FIELD.has_default_value = false
RSPSETROLE_ROLEID_FIELD.default_value = 0
RSPSETROLE_ROLEID_FIELD.type = 5
RSPSETROLE_ROLEID_FIELD.cpp_type = 1

RSPSETROLE_ROLENAME_FIELD.name = "roleName"
RSPSETROLE_ROLENAME_FIELD.full_name = ".RspSetRole.roleName"
RSPSETROLE_ROLENAME_FIELD.number = 2
RSPSETROLE_ROLENAME_FIELD.index = 1
RSPSETROLE_ROLENAME_FIELD.label = 2
RSPSETROLE_ROLENAME_FIELD.has_default_value = false
RSPSETROLE_ROLENAME_FIELD.default_value = ""
RSPSETROLE_ROLENAME_FIELD.type = 9
RSPSETROLE_ROLENAME_FIELD.cpp_type = 9

RSPSETROLE_ATK_FIELD.name = "atk"
RSPSETROLE_ATK_FIELD.full_name = ".RspSetRole.atk"
RSPSETROLE_ATK_FIELD.number = 3
RSPSETROLE_ATK_FIELD.index = 2
RSPSETROLE_ATK_FIELD.label = 2
RSPSETROLE_ATK_FIELD.has_default_value = false
RSPSETROLE_ATK_FIELD.default_value = 0
RSPSETROLE_ATK_FIELD.type = 5
RSPSETROLE_ATK_FIELD.cpp_type = 1

RSPSETROLE_DEF_FIELD.name = "def"
RSPSETROLE_DEF_FIELD.full_name = ".RspSetRole.def"
RSPSETROLE_DEF_FIELD.number = 4
RSPSETROLE_DEF_FIELD.index = 3
RSPSETROLE_DEF_FIELD.label = 2
RSPSETROLE_DEF_FIELD.has_default_value = false
RSPSETROLE_DEF_FIELD.default_value = 0
RSPSETROLE_DEF_FIELD.type = 5
RSPSETROLE_DEF_FIELD.cpp_type = 1

RSPSETROLE_HP_FIELD.name = "Hp"
RSPSETROLE_HP_FIELD.full_name = ".RspSetRole.Hp"
RSPSETROLE_HP_FIELD.number = 5
RSPSETROLE_HP_FIELD.index = 4
RSPSETROLE_HP_FIELD.label = 2
RSPSETROLE_HP_FIELD.has_default_value = false
RSPSETROLE_HP_FIELD.default_value = 0
RSPSETROLE_HP_FIELD.type = 5
RSPSETROLE_HP_FIELD.cpp_type = 1

RSPSETROLE.name = "RspSetRole"
RSPSETROLE.full_name = ".RspSetRole"
RSPSETROLE.nested_types = {}
RSPSETROLE.enum_types = {}
RSPSETROLE.fields = {RSPSETROLE_ROLEID_FIELD, RSPSETROLE_ROLENAME_FIELD, RSPSETROLE_ATK_FIELD, RSPSETROLE_DEF_FIELD, RSPSETROLE_HP_FIELD}
RSPSETROLE.is_extendable = false
RSPSETROLE.extensions = {}

ReqBuyRole = protobuf.Message(REQBUYROLE)
ReqSetRole = protobuf.Message(REQSETROLE)
RspBuyRole = protobuf.Message(RSPBUYROLE)
RspSetRole = protobuf.Message(RSPSETROLE)

