//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Singleton_LuaBattleManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Singleton<LuaBattleManager>), typeof(System.Object), "Singleton_LuaBattleManager");
		L.RegFunction("New", _CreateSingleton_LuaBattleManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingleton_LuaBattleManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Singleton<LuaBattleManager> obj = new Singleton<LuaBattleManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Singleton<LuaBattleManager>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Singleton<LuaBattleManager>.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

