-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local common_pb = require("common_pb")
module('bag_pb')


local REQGETITEMINFO = protobuf.Descriptor();
local RSPGETITEMINFO = protobuf.Descriptor();
local RSPGETITEMINFO_INVS_FIELD = protobuf.FieldDescriptor();

REQGETITEMINFO.name = "ReqGetItemInfo"
REQGETITEMINFO.full_name = ".ReqGetItemInfo"
REQGETITEMINFO.nested_types = {}
REQGETITEMINFO.enum_types = {}
REQGETITEMINFO.fields = {}
REQGETITEMINFO.is_extendable = false
REQGETITEMINFO.extensions = {}
RSPGETITEMINFO_INVS_FIELD.name = "invs"
RSPGETITEMINFO_INVS_FIELD.full_name = ".RspGetItemInfo.invs"
RSPGETITEMINFO_INVS_FIELD.number = 1
RSPGETITEMINFO_INVS_FIELD.index = 0
RSPGETITEMINFO_INVS_FIELD.label = 3
RSPGETITEMINFO_INVS_FIELD.has_default_value = false
RSPGETITEMINFO_INVS_FIELD.default_value = {}
RSPGETITEMINFO_INVS_FIELD.message_type = COMMON_PB_INVENTORYDTO
RSPGETITEMINFO_INVS_FIELD.type = 11
RSPGETITEMINFO_INVS_FIELD.cpp_type = 10

RSPGETITEMINFO.name = "RspGetItemInfo"
RSPGETITEMINFO.full_name = ".RspGetItemInfo"
RSPGETITEMINFO.nested_types = {}
RSPGETITEMINFO.enum_types = {}
RSPGETITEMINFO.fields = {RSPGETITEMINFO_INVS_FIELD}
RSPGETITEMINFO.is_extendable = false
RSPGETITEMINFO.extensions = {}

ReqGetItemInfo = protobuf.Message(REQGETITEMINFO)
RspGetItemInfo = protobuf.Message(RSPGETITEMINFO)

