-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local common_pb = require("common_pb")
module('mall_pb')


local REQBUY = protobuf.Descriptor();
local REQBUY_ID_FIELD = protobuf.FieldDescriptor();
local REQBUY_ITEMID_FIELD = protobuf.FieldDescriptor();
local RSPBUY = protobuf.Descriptor();
local RSPBUY_LASTGOLD_FIELD = protobuf.FieldDescriptor();
local RSPBUY_LASTDIAMOND_FIELD = protobuf.FieldDescriptor();
local RSPBUY_MSGTIPS_FIELD = protobuf.FieldDescriptor();
local RSPBUY_ITEMID_FIELD = protobuf.FieldDescriptor();

REQBUY_ID_FIELD.name = "id"
REQBUY_ID_FIELD.full_name = ".ReqBuy.id"
REQBUY_ID_FIELD.number = 1
REQBUY_ID_FIELD.index = 0
REQBUY_ID_FIELD.label = 2
REQBUY_ID_FIELD.has_default_value = false
REQBUY_ID_FIELD.default_value = 0
REQBUY_ID_FIELD.type = 5
REQBUY_ID_FIELD.cpp_type = 1

REQBUY_ITEMID_FIELD.name = "itemId"
REQBUY_ITEMID_FIELD.full_name = ".ReqBuy.itemId"
REQBUY_ITEMID_FIELD.number = 4
REQBUY_ITEMID_FIELD.index = 1
REQBUY_ITEMID_FIELD.label = 2
REQBUY_ITEMID_FIELD.has_default_value = false
REQBUY_ITEMID_FIELD.default_value = 0
REQBUY_ITEMID_FIELD.type = 5
REQBUY_ITEMID_FIELD.cpp_type = 1

REQBUY.name = "ReqBuy"
REQBUY.full_name = ".ReqBuy"
REQBUY.nested_types = {}
REQBUY.enum_types = {}
REQBUY.fields = {REQBUY_ID_FIELD, REQBUY_ITEMID_FIELD}
REQBUY.is_extendable = false
REQBUY.extensions = {}
RSPBUY_LASTGOLD_FIELD.name = "lastGold"
RSPBUY_LASTGOLD_FIELD.full_name = ".RspBuy.lastGold"
RSPBUY_LASTGOLD_FIELD.number = 1
RSPBUY_LASTGOLD_FIELD.index = 0
RSPBUY_LASTGOLD_FIELD.label = 2
RSPBUY_LASTGOLD_FIELD.has_default_value = false
RSPBUY_LASTGOLD_FIELD.default_value = 0
RSPBUY_LASTGOLD_FIELD.type = 5
RSPBUY_LASTGOLD_FIELD.cpp_type = 1

RSPBUY_LASTDIAMOND_FIELD.name = "lastDiamond"
RSPBUY_LASTDIAMOND_FIELD.full_name = ".RspBuy.lastDiamond"
RSPBUY_LASTDIAMOND_FIELD.number = 2
RSPBUY_LASTDIAMOND_FIELD.index = 1
RSPBUY_LASTDIAMOND_FIELD.label = 2
RSPBUY_LASTDIAMOND_FIELD.has_default_value = false
RSPBUY_LASTDIAMOND_FIELD.default_value = 0
RSPBUY_LASTDIAMOND_FIELD.type = 5
RSPBUY_LASTDIAMOND_FIELD.cpp_type = 1

RSPBUY_MSGTIPS_FIELD.name = "msgtips"
RSPBUY_MSGTIPS_FIELD.full_name = ".RspBuy.msgtips"
RSPBUY_MSGTIPS_FIELD.number = 3
RSPBUY_MSGTIPS_FIELD.index = 2
RSPBUY_MSGTIPS_FIELD.label = 2
RSPBUY_MSGTIPS_FIELD.has_default_value = false
RSPBUY_MSGTIPS_FIELD.default_value = 0
RSPBUY_MSGTIPS_FIELD.type = 13
RSPBUY_MSGTIPS_FIELD.cpp_type = 3

RSPBUY_ITEMID_FIELD.name = "itemId"
RSPBUY_ITEMID_FIELD.full_name = ".RspBuy.itemId"
RSPBUY_ITEMID_FIELD.number = 4
RSPBUY_ITEMID_FIELD.index = 3
RSPBUY_ITEMID_FIELD.label = 2
RSPBUY_ITEMID_FIELD.has_default_value = false
RSPBUY_ITEMID_FIELD.default_value = 0
RSPBUY_ITEMID_FIELD.type = 5
RSPBUY_ITEMID_FIELD.cpp_type = 1

RSPBUY.name = "RspBuy"
RSPBUY.full_name = ".RspBuy"
RSPBUY.nested_types = {}
RSPBUY.enum_types = {}
RSPBUY.fields = {RSPBUY_LASTGOLD_FIELD, RSPBUY_LASTDIAMOND_FIELD, RSPBUY_MSGTIPS_FIELD, RSPBUY_ITEMID_FIELD}
RSPBUY.is_extendable = false
RSPBUY.extensions = {}

ReqBuy = protobuf.Message(REQBUY)
RspBuy = protobuf.Message(RSPBUY)

