---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shang.
--- DateTime: 2018/3/12 14:38
---
require("View.MainWnd")

MainScene = {}

local this = MainScene;

function MainScene.Initialize()
    MainWnd.Open()
end

function MainScene.Finalize()
    MainWnd.Close()
end